spring:
  application:
    name: "bachelor-thesis-server"
  datasource:
    url:
    username:
    password:

application:
  endpoint:
    root: /api
    doctorNote: /doctorNotes
    doctor: /doctors
    institution: /institutions
    patient: /patients
    scheduleElement: /scheduleElements
    scheduleElementStatus: /scheduleElementStatuses
    scheduledVisit: /scheduledVisits
    service: /services
    unscheduledVisit: /unscheduledVisits
    application: /applications
    applicationStatus: /applicationStatuses
