spring:
  application:
    name: "bachelor-thesis-server"
  datasource:
    url:
    username:
    password:

application:
  endpoint:
    root: /api
    doctorNote: /doctorNote
    employee: /employee
    institution: /institution
    patient: /patient
    planElement: /planElement
    planElementStatus: /planElementStatus
    planElementType: /planElementType
    scheduled: /scheduled
    services: /service
    unscheduled: /unscheduled
    visit: /visit
    visitStatus: /visitStatus
    visitType: /visitType